Added exit on all exceptions to avoid  errors
CodeSpaceHQ/SDA pull request #12
Opened 2017-03-16 05:39 UTC by dlowrey

Just made a few adjustments. I will create the SQL to match the table schemes in a different branch.

2017-03-16 16:28 UTC, asclines commented
@dlowrey so is not to be merged?

2017-03-18 17:51 UTC, dlowrey commented
I wasn't sure if this is how I was supposed to go about making small changes.

2017-03-18 18:37 UTC, asclines commented
@dlowrey Well pull-request is the only way to make any changes to `master` so yeah. Don't worry about it being too small. As long as the modification is complete, feel free to PR

2017-03-18 18:46 UTC, dlowrey commented
@asclines I am going to make the SQL Table schema changes then PR

2017-03-18 18:47 UTC, asclines commented
@dlowrey then update this PR comment

2017-03-18 19:59 UTC, asclines commented on initdb.py
> +    "   `COUNTY` varchar(20) NOT NULL,"
Is 20 enough? I haven't personally checked with the datasets yet.

2017-03-18 20:02 UTC, dlowrey commented on initdb.py
> +    "   `COUNTY` varchar(20) NOT NULL,"
It probably isn't now that I think of it. How long should it be?

2017-03-18 20:56 UTC, asclines commented on initdb.py
> +    "   `COUNTY` varchar(20) NOT NULL,"
According to [here](http://www.funtrivia.com/askft/Question33835.html) you only need 14.
[Here](http://boards.straightdope.com/sdmb/showthread.php?t=783204) is a much funnier conversation.

All in all, 50 should be good.

2017-03-20 01:22 UTC, asclines requested changes
When testing this code, I found that it crashes when a user inputs wrong username and password. 

```
Username or Password was incorrect.
Traceback (most recent call last):
  File "initdb.py", line 123, in <module>
    connection_cursor = mysql_connection.cursor()
NameError: name 'mysql_connection' is not defined
```

**Note:** This error is actually thrown from the master branch code so the line number may be off.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +    if username == "" or password=="":
Exactly one space required around comparison.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +
Trailing newline here, remove.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +DATASETS['income'] = csv.reader(open('datasets\income-data.csv'))
Don't use `\` use `/`. This will _only_ work on a Windows machine.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +DATASETS['starbucks'] = csv.reader(open('datasets\\starbucks.csv'))
Don't use `\` use `/`. This will _only_ work on a Windows machine.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +DATASETS['diversity'] = csv.reader(open('datasets\\diversity.csv'))
Don't use `\` use `/`. This will _only_ work on a Windows machine.

2017-03-20 01:22 UTC, asclines commented on initdb.py
>  def create_database(cursor, connection):
`connection` is never used.

2017-03-20 01:22 UTC, asclines commented on initdb.py
> +def insert_data(cursor, connection):
`connection` is never used.

2017-03-20 01:35 UTC, asclines requested changes

2017-03-20 01:35 UTC, asclines commented on initdb.py
> +    "   `CITY` char(50) NOT NULL,"
This should be `varchar(50)`

2017-03-20 01:35 UTC, asclines commented on initdb.py
> +    "   `ZIPCODE` varchar(25) NOT NULL,"
Shouldn't this be a `char(5)` ?

2017-03-20 01:35 UTC, asclines commented on initdb.py
> +    "   `CITY` char(50) NOT NULL,"
This should be `varchar(50)`

2017-03-20 01:35 UTC, asclines commented on initdb.py
> +    "   `COUNTY` char(50) NOT NULL,"
This should be `varchar(50)`

2017-03-20 22:48 UTC, asclines requested changes
Two things:
1. Update the `.gitignore` to include `.idea/` folder
2. Also, you have several print statements, if this module is to be imported into another module, this should throw errors instead of printing errors.

2017-03-20 22:48 UTC, asclines commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
REMOVE THIS FILE

2017-03-20 22:48 UTC, asclines commented on initdb.py
> +from time import sleep
This is never used.

2017-03-20 22:48 UTC, asclines commented on initdb.py
> +    print("Database set up completed.")
For safe measures, add a newline here. Just 1

2017-03-20 22:48 UTC, asclines commented on initdb.py
> +    if __name__ == '__main__': main()
What is the purpose of this line?

2017-03-20 23:08 UTC, dlowrey commented on initdb.py
> +    if __name__ == '__main__': main()
This line should be outside of the main function,  I will move it.

2017-03-21 01:26 UTC, dlowrey commented on initdb.py
> +
Removed it

2017-03-21 01:27 UTC, dlowrey commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
added `.idea/` folder to `.gitignore`

2017-03-21 02:24 UTC, asclines requested changes
Getting there!

2017-03-21 02:24 UTC, asclines commented on initdb.py
>  # 6) exit
1) Now that (5) is gone, the numbering is messed up
2) I'm not really sure this is even needed.

@ASAAR thoughts?

2017-03-21 02:24 UTC, asclines commented on initdb.py
>  import sys
This import is now no longer used.

2017-03-21 02:24 UTC, asclines commented on initdb.py
>  from mysql.connector import errorcode
This import is now no longer used.

2017-03-21 02:24 UTC, asclines commented on initdb.py
>      except mysql.connector.Error as mysqlError:
`mysqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

2017-03-21 02:24 UTC, asclines commented on initdb.py
>      except mysql.connector.Error as mysqlError:
`mysqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

2017-03-21 02:24 UTC, asclines commented on initdb.py
>          except mysql.connector.Error as mysqlError:
`mysqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

2017-03-21 02:24 UTC, asclines commented on initdb.py
> +if __name__ == '__main__': main()
This allows exceptions to reach the console when true. You should have exception handling here.

2017-03-21 02:30 UTC, dlowrey commented on initdb.py
> +if __name__ == '__main__': main()
Should I just catch all exceptions?

2017-03-21 02:38 UTC, asclines commented on initdb.py
> +if __name__ == '__main__': main()
It would be better if you caught specific exceptions that you were expecting so you can print to console helpful output.

2017-03-21 02:42 UTC, dlowrey commented on initdb.py
> +if __name__ == '__main__': main()
Got it

2017-03-21 03:34 UTC, asclines requested changes
Please read [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

2017-03-21 03:34 UTC, asclines commented on initdb.py
> +    except mysql.connector.Error as MySqlError:
`MySqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

make it something like: `mysql_error`

2017-03-21 03:34 UTC, asclines commented on initdb.py
> +    except mysql.connector.Error as MySqlError:
`MySqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

make it something like: `mysql_error`

2017-03-21 03:34 UTC, asclines commented on initdb.py
> +        except mysql.connector.Error as MySqlError:
`MySqlError` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

make it something like: `mysql_error`

2017-03-21 03:34 UTC, asclines commented on initdb.py
>              print("OK")
This is probably not needed anymore. We can assume OK upon completion without error.

2017-03-21 03:34 UTC, asclines commented on initdb.py
> +    except Exception as InitDbException:
`InitDbException` violates [Google Python Style Guide: Naming](https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming)

make it something like: `db_exception`

I also would recommend placing a TODO here to mark that in the future exception handling here shouldn't be so broad.

2017-03-21 03:34 UTC, asclines commented on initdb.py
>      print("Database set up completed.")
This is probably not needed anymore. We can assume OK upon completion without error.

2017-03-21 04:08 UTC, dlowrey commented on initdb.py
> +    except Exception as InitDbException:
I thought the style guide for exceptions was CapWords?

2017-03-21 04:14 UTC, dlowrey commented
Good god this PR. @asclines is ruthless

2017-03-22 03:14 UTC, asclines commented
@dlowrey now that the custom exception class is created in 470b7b028298f7b24c40ecbb63ccdbef41fd7ad3 
can you create a `MySqlError` and then implement the errors in the `initdb.py` code?

2017-03-24 05:15 UTC, dlowrey commented
@asclines I have replaced all of the exception handling with `MySqlError` and `InputError`, I do not know what exactly to do in the try/catch below the `if __name__ == '__main__':...` though.

2017-03-24 19:20 UTC, asclines requested changes
Almost there. 
So the reason we have the `args` parameter is to hold the original error. The end-user doesn't need to see that. We as developers can check the `args` parameter in a DEBUG mode if we want to see the real error.

2017-03-24 19:20 UTC, asclines commented on exceptions.py
>  # TODO(asclines): There needs to be another exception for MySQL errors
This TODO can be removed now

2017-03-24 19:20 UTC, asclines commented on exceptions.py
> +        :Args:
The first : is unneeded

2017-03-24 19:20 UTC, asclines commented on initdb.py
> +from exceptions import *
Don't use wildcard imports like this. See [here](http://stackoverflow.com/a/193931/4167059) for a couple examples.

2017-03-24 19:20 UTC, asclines commented on initdb.py
> +    except (InputError, MySqlError) as db_exception:
✔️

2017-03-24 19:20 UTC, asclines commented on initdb.py
> +        raise MySqlError(message='Failed creating database: {}'.format(mysql_error),
Don't put `mysql_error` in the message. The end-user doesn't need to see the stacktrace or original error. That's why we have `args`.

2017-03-24 19:20 UTC, asclines commented on initdb.py
> +        raise InputError(message='There was a problem connecting to the server:\n{}'.format(err),
Don't put `err` in the message. The end-user doesn't need to see the stacktrace or original error. That's why we have `args`.

2017-03-24 19:20 UTC, asclines commented on initdb.py
> +        raise MySqlError(message='There was a problem connecting to the database {}:\n{}'.format(DB_NAME, mysql_error),
Don't put `mysql_error` in the message. The end-user doesn't need to see the stacktrace or original error. That's why we have `args`.

2017-03-24 20:54 UTC, asclines requested changes

2017-03-24 20:54 UTC, asclines commented on initdb.py
> +from exceptions import InputError, MySqlError
Switch lines 5 & 6. See Google Python Style Guide's [Import Formatting](https://google.github.io/styleguide/pyguide.html?showone=Imports_formatting#Imports_formatting)

2017-03-24 21:32 UTC, asclines approved these changes
Tested on my machine all looks good.

In the future we should look into [`executemany`](https://dev.mysql.com/doc/connectors/en/connector-python-api-mysqlcursor-executemany.html)  for the executions.

2017-03-24 21:38 UTC, isaac-gs approved these changes
Looks good, a lot cleaner

2017-03-24 21:45 UTC, merged