Initdb refactor
CodeSpaceHQ/SDA pull request #19
Opened 2017-04-13 15:30 UTC by dlowrey

Refactored the `initdb.py` script to make it more concise and clean. 

Changes include:

- Reorganization of functions to connect, initialize database, and insert data
- Correct implementation of transactions with rollbacks when inserting data
- Optimization inserting data with `executemany()` instead of `execute()`
- Noticeable execution time increse
- Overall cleaned up methods and comments

2017-04-13 16:27 UTC, asclines requested changes
I liked the refactoring done on `initdb.py`

2017-04-13 16:27 UTC, asclines commented on dbmanager.py
> +from exceptions import InputError, MySqlError
Pylint output: 
> ************* Module dbmanager
C:  8, 0: Trailing whitespace (trailing-whitespace)
C: 11, 0: Trailing whitespace (trailing-whitespace)
C: 14, 0: Trailing whitespace (trailing-whitespace)
C: 24, 0: Wrong continued indentation (remove 1 space).
                                              password=password,
                                             |^ (bad-continuation)
C: 25, 0: Wrong continued indentation (remove 1 space).
                                              database=DB_NAME)
                                             |^ (bad-continuation)
C: 34, 0: Trailing whitespace (trailing-whitespace)
C: 37, 0: Trailing whitespace (trailing-whitespace)
C: 40, 0: Trailing whitespace (trailing-whitespace)
C: 53, 0: Wrong continued indentation (remove 2 spaces).
                             args=err.args)
                           | ^ (bad-continuation)
~C:  1, 0: Missing module docstring (missing-docstring)~

Ignored crossed out ones.

2017-04-13 16:27 UTC, asclines commented on initdb.py
>  import os
Pylint output:
> ************* Module initdb
C: 85, 0: Trailing whitespace (trailing-whitespace)
C:140, 0: Trailing whitespace (trailing-whitespace)
C:144, 0: Trailing whitespace (trailing-whitespace)
C:150, 0: Trailing whitespace (trailing-whitespace)
~C:  1, 0: Missing module docstring (missing-docstring)~ 

Ignore crossed out ones.

2017-04-13 16:27 UTC, asclines commented on dbmanager.py
> +    :raises An InputError (likely because no username or password was provided)
Is there anytime this actually happens? Wouldn't an exception just be thrown?

2017-04-13 16:27 UTC, asclines commented on dbmanager.py
> +                MySqlError(message='There was a problem executing your query.',
Is it possible to include what the SQL statement was in this exception?

Or is this handled by `args`?

2017-04-13 16:27 UTC, asclines commented on dbmanager.py
> +def exec_sql(connection, sql=None):
Why `sql=None`? Is there a scenario where we don't want SQL to be supplied?

2017-04-13 16:27 UTC, asclines commented on initdb.py
> +def init_connections(username=None, password=None):
Is this the same as the `init_connection` method in `dbmanager.py`?

2017-04-13 17:10 UTC, dlowrey commented on initdb.py
> +def init_connections(username=None, password=None):
Oh shoot I didn't realize it pushed my dbmanager changes too. I wasn't near finished with dbmanager

2017-04-13 17:11 UTC, dlowrey commented
Oh shoot I didn't realize it pushed my dbmanager changes too. I wasn't near finished with dbmanager

2017-04-14 16:09 UTC, dlowrey commented
I will clean up `dbmanager.py` to just include the connecting method and the method signature for running SQL queries and we can implement them later.

2017-04-14 16:25 UTC, dlowrey commented on initdb.py
> +def init_connections(username=None, password=None):
Yes

2017-04-14 16:28 UTC, asclines commented
@dlowrey implement what later?

2017-04-14 16:29 UTC, dlowrey commented
@asclines I decided that the functionality was already there so I just cleaned it up.

2017-04-14 16:31 UTC, asclines approved these changes

2017-04-14 16:31 UTC, dlowrey commented on initdb.py
>  import os
@asclines It really doesn't like the whitespace left between the Doc-string comments?

2017-04-14 16:31 UTC, asclines commented
Approving with the expectation that more changes will come later.

2017-04-15 01:07 UTC, merged